name: Test

on:
  workflow_call:
    inputs:
      role:
        required: false
        type: string
      config_file_contents:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '11'
      working-directory:
        required: false
        type: string
        default: '.'
    secrets:
      AWS_ACCOUNT_ID:
        required: false
      AWS_REGION:
        required: false
      USER_NAME:
        required: true
      ACCESS_TOKEN:
        required: true
      PACKAGE_REPO:
        required: true

jobs:
  maven-clean-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Branch from GitHub
        uses: actions/checkout@v4

      - name: Install Java Corretto ${{inputs.java_version}}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '${{inputs.java_version}}'
          cache: 'maven'

      - name: Generate Maven settings.xml file to access GitHub Packages
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "${{secrets.PACKAGE_REPO}}",
                "releases": {
                  "enabled": "true"
                  },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${{secrets.USER_NAME}}",
                "password": "${{secrets.ACCESS_TOKEN}}"
              }
            ]
          active_profiles: >
            [
              "github"
            ]
      - name: Generate settings.yaml File Inside Repository
        uses: 1arp/create-a-file-action@v0.4.5
        with:
          path: 'config'
          file: 'settings.yaml'
          content: |
            ${{inputs.config_file_contents}}

      - name: ðŸ”‘ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        if: ${{ env.AWS_ACCOUNT_ID && inputs.role }}
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{inputs.role}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Unit Tests with Maven
        run: |
          aws configure set region eu-west-1
          mvn clean test --no-transfer-progress
        working-directory: ${{inputs.working-directory}}

